// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: branches.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createBranch = `-- name: CreateBranch :one
INSERT INTO branches (
    name,
    code,
    address,
    tax_code,
    phone,
    status
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, name, code, address, tax_code, phone, status, created_at
`

type CreateBranchParams struct {
	Name    string      `json:"name"`
	Code    string      `json:"code"`
	Address pgtype.Text `json:"address"`
	TaxCode pgtype.Text `json:"tax_code"`
	Phone   pgtype.Text `json:"phone"`
	Status  pgtype.Text `json:"status"`
}

func (q *Queries) CreateBranch(ctx context.Context, arg CreateBranchParams) (Branch, error) {
	row := q.db.QueryRow(ctx, createBranch,
		arg.Name,
		arg.Code,
		arg.Address,
		arg.TaxCode,
		arg.Phone,
		arg.Status,
	)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Address,
		&i.TaxCode,
		&i.Phone,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const deleteBranch = `-- name: DeleteBranch :exec
DELETE FROM branches
WHERE id = $1
`

func (q *Queries) DeleteBranch(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteBranch, id)
	return err
}

const getBranch = `-- name: GetBranch :one
SELECT id, name, code, address, tax_code, phone, status, created_at FROM branches
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetBranch(ctx context.Context, id uuid.UUID) (Branch, error) {
	row := q.db.QueryRow(ctx, getBranch, id)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Address,
		&i.TaxCode,
		&i.Phone,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getBranchByCode = `-- name: GetBranchByCode :one
SELECT id, name, code, address, tax_code, phone, status, created_at FROM branches
WHERE code = $1 LIMIT 1
`

func (q *Queries) GetBranchByCode(ctx context.Context, code string) (Branch, error) {
	row := q.db.QueryRow(ctx, getBranchByCode, code)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Address,
		&i.TaxCode,
		&i.Phone,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listBranches = `-- name: ListBranches :many
SELECT id, name, code, address, tax_code, phone, status, created_at FROM branches
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListBranchesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListBranches(ctx context.Context, arg ListBranchesParams) ([]Branch, error) {
	rows, err := q.db.Query(ctx, listBranches, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Branch{}
	for rows.Next() {
		var i Branch
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.Address,
			&i.TaxCode,
			&i.Phone,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBranch = `-- name: UpdateBranch :one
UPDATE branches
SET
    name = COALESCE($2, name),
    address = COALESCE($3, address),
    tax_code = COALESCE($4, tax_code),
    phone = COALESCE($5, phone),
    status = COALESCE($6, status)
WHERE id = $1
RETURNING id, name, code, address, tax_code, phone, status, created_at
`

type UpdateBranchParams struct {
	ID      uuid.UUID   `json:"id"`
	Name    string      `json:"name"`
	Address pgtype.Text `json:"address"`
	TaxCode pgtype.Text `json:"tax_code"`
	Phone   pgtype.Text `json:"phone"`
	Status  pgtype.Text `json:"status"`
}

func (q *Queries) UpdateBranch(ctx context.Context, arg UpdateBranchParams) (Branch, error) {
	row := q.db.QueryRow(ctx, updateBranch,
		arg.ID,
		arg.Name,
		arg.Address,
		arg.TaxCode,
		arg.Phone,
		arg.Status,
	)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Address,
		&i.TaxCode,
		&i.Phone,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
