// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: campaigns.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCampaign = `-- name: CreateCampaign :one
INSERT INTO campaigns (
    name,
    budget,
    start_date,
    end_date,
    platform,
    status
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, name, budget, start_date, end_date, platform, status
`

type CreateCampaignParams struct {
	Name      string         `json:"name"`
	Budget    pgtype.Numeric `json:"budget"`
	StartDate pgtype.Date    `json:"start_date"`
	EndDate   pgtype.Date    `json:"end_date"`
	Platform  pgtype.Text    `json:"platform"`
	Status    pgtype.Text    `json:"status"`
}

func (q *Queries) CreateCampaign(ctx context.Context, arg CreateCampaignParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, createCampaign,
		arg.Name,
		arg.Budget,
		arg.StartDate,
		arg.EndDate,
		arg.Platform,
		arg.Status,
	)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Budget,
		&i.StartDate,
		&i.EndDate,
		&i.Platform,
		&i.Status,
	)
	return i, err
}

const getCampaign = `-- name: GetCampaign :one
SELECT id, name, budget, start_date, end_date, platform, status FROM campaigns
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCampaign(ctx context.Context, id uuid.UUID) (Campaign, error) {
	row := q.db.QueryRow(ctx, getCampaign, id)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Budget,
		&i.StartDate,
		&i.EndDate,
		&i.Platform,
		&i.Status,
	)
	return i, err
}

const listCampaigns = `-- name: ListCampaigns :many
SELECT id, name, budget, start_date, end_date, platform, status FROM campaigns
ORDER BY start_date DESC
LIMIT $1 OFFSET $2
`

type ListCampaignsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListCampaigns(ctx context.Context, arg ListCampaignsParams) ([]Campaign, error) {
	rows, err := q.db.Query(ctx, listCampaigns, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Campaign{}
	for rows.Next() {
		var i Campaign
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Budget,
			&i.StartDate,
			&i.EndDate,
			&i.Platform,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
