// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contracts.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createContract = `-- name: CreateContract :one
INSERT INTO contracts (
    order_id,
    contract_number,
    signed_date,
    file_url
) VALUES (
    $1, $2, $3, $4
) RETURNING id, order_id, contract_number, signed_date, file_url, created_at
`

type CreateContractParams struct {
	OrderID        uuid.UUID   `json:"order_id"`
	ContractNumber string      `json:"contract_number"`
	SignedDate     pgtype.Date `json:"signed_date"`
	FileUrl        pgtype.Text `json:"file_url"`
}

func (q *Queries) CreateContract(ctx context.Context, arg CreateContractParams) (Contract, error) {
	row := q.db.QueryRow(ctx, createContract,
		arg.OrderID,
		arg.ContractNumber,
		arg.SignedDate,
		arg.FileUrl,
	)
	var i Contract
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ContractNumber,
		&i.SignedDate,
		&i.FileUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getContractByOrder = `-- name: GetContractByOrder :one
SELECT id, order_id, contract_number, signed_date, file_url, created_at FROM contracts
WHERE order_id = $1 LIMIT 1
`

func (q *Queries) GetContractByOrder(ctx context.Context, orderID uuid.UUID) (Contract, error) {
	row := q.db.QueryRow(ctx, getContractByOrder, orderID)
	var i Contract
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ContractNumber,
		&i.SignedDate,
		&i.FileUrl,
		&i.CreatedAt,
	)
	return i, err
}
