// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: customers.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customers (
    type,
    name,
    phone,
    email,
    id_card_number,
    address
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, type, name, phone, email, id_card_number, address, created_at
`

type CreateCustomerParams struct {
	Type         pgtype.Text `json:"type"`
	Name         string      `json:"name"`
	Phone        string      `json:"phone"`
	Email        pgtype.Text `json:"email"`
	IDCardNumber pgtype.Text `json:"id_card_number"`
	Address      pgtype.Text `json:"address"`
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, createCustomer,
		arg.Type,
		arg.Name,
		arg.Phone,
		arg.Email,
		arg.IDCardNumber,
		arg.Address,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.IDCardNumber,
		&i.Address,
		&i.CreatedAt,
	)
	return i, err
}

const getCustomer = `-- name: GetCustomer :one
SELECT id, type, name, phone, email, id_card_number, address, created_at FROM customers
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCustomer(ctx context.Context, id uuid.UUID) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomer, id)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.IDCardNumber,
		&i.Address,
		&i.CreatedAt,
	)
	return i, err
}

const getCustomerByPhone = `-- name: GetCustomerByPhone :one
SELECT id, type, name, phone, email, id_card_number, address, created_at FROM customers
WHERE phone = $1 LIMIT 1
`

func (q *Queries) GetCustomerByPhone(ctx context.Context, phone string) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerByPhone, phone)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.IDCardNumber,
		&i.Address,
		&i.CreatedAt,
	)
	return i, err
}

const listCustomers = `-- name: ListCustomers :many
SELECT id, type, name, phone, email, id_card_number, address, created_at FROM customers
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListCustomersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListCustomers(ctx context.Context, arg ListCustomersParams) ([]Customer, error) {
	rows, err := q.db.Query(ctx, listCustomers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Customer{}
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Name,
			&i.Phone,
			&i.Email,
			&i.IDCardNumber,
			&i.Address,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchCustomers = `-- name: SearchCustomers :many
SELECT id, type, name, phone, email, id_card_number, address, created_at FROM customers
WHERE name ILIKE $1 OR phone ILIKE $1 OR id_card_number ILIKE $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type SearchCustomersParams struct {
	Name   string `json:"name"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) SearchCustomers(ctx context.Context, arg SearchCustomersParams) ([]Customer, error) {
	rows, err := q.db.Query(ctx, searchCustomers, arg.Name, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Customer{}
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Name,
			&i.Phone,
			&i.Email,
			&i.IDCardNumber,
			&i.Address,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCustomer = `-- name: UpdateCustomer :one
UPDATE customers
SET
    type = COALESCE($2, type),
    name = COALESCE($3, name),
    phone = COALESCE($4, phone),
    email = COALESCE($5, email),
    id_card_number = COALESCE($6, id_card_number),
    address = COALESCE($7, address)
WHERE id = $1
RETURNING id, type, name, phone, email, id_card_number, address, created_at
`

type UpdateCustomerParams struct {
	ID           uuid.UUID   `json:"id"`
	Type         pgtype.Text `json:"type"`
	Name         string      `json:"name"`
	Phone        string      `json:"phone"`
	Email        pgtype.Text `json:"email"`
	IDCardNumber pgtype.Text `json:"id_card_number"`
	Address      pgtype.Text `json:"address"`
}

func (q *Queries) UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, updateCustomer,
		arg.ID,
		arg.Type,
		arg.Name,
		arg.Phone,
		arg.Email,
		arg.IDCardNumber,
		arg.Address,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.IDCardNumber,
		&i.Address,
		&i.CreatedAt,
	)
	return i, err
}
