// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: departments.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createDepartment = `-- name: CreateDepartment :one
INSERT INTO departments (
    name
) VALUES (
    $1
) RETURNING id, name
`

func (q *Queries) CreateDepartment(ctx context.Context, name string) (Department, error) {
	row := q.db.QueryRow(ctx, createDepartment, name)
	var i Department
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getDepartment = `-- name: GetDepartment :one
SELECT id, name FROM departments
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetDepartment(ctx context.Context, id uuid.UUID) (Department, error) {
	row := q.db.QueryRow(ctx, getDepartment, id)
	var i Department
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const listDepartments = `-- name: ListDepartments :many
SELECT id, name FROM departments
ORDER BY name ASC
`

func (q *Queries) ListDepartments(ctx context.Context) ([]Department, error) {
	rows, err := q.db.Query(ctx, listDepartments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Department{}
	for rows.Next() {
		var i Department
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
