// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: employees.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createEmployee = `-- name: CreateEmployee :one
INSERT INTO employees (
    branch_id,
    department_id,
    full_name,
    email,
    phone,
    position,
    hire_date,
    status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, branch_id, department_id, full_name, email, phone, position, hire_date, status, created_at
`

type CreateEmployeeParams struct {
	BranchID     uuid.UUID   `json:"branch_id"`
	DepartmentID uuid.UUID   `json:"department_id"`
	FullName     string      `json:"full_name"`
	Email        string      `json:"email"`
	Phone        pgtype.Text `json:"phone"`
	Position     pgtype.Text `json:"position"`
	HireDate     pgtype.Date `json:"hire_date"`
	Status       pgtype.Text `json:"status"`
}

func (q *Queries) CreateEmployee(ctx context.Context, arg CreateEmployeeParams) (Employee, error) {
	row := q.db.QueryRow(ctx, createEmployee,
		arg.BranchID,
		arg.DepartmentID,
		arg.FullName,
		arg.Email,
		arg.Phone,
		arg.Position,
		arg.HireDate,
		arg.Status,
	)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.DepartmentID,
		&i.FullName,
		&i.Email,
		&i.Phone,
		&i.Position,
		&i.HireDate,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const deleteEmployee = `-- name: DeleteEmployee :exec
DELETE FROM employees
WHERE id = $1
`

func (q *Queries) DeleteEmployee(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEmployee, id)
	return err
}

const getEmployee = `-- name: GetEmployee :one
SELECT id, branch_id, department_id, full_name, email, phone, position, hire_date, status, created_at FROM employees
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetEmployee(ctx context.Context, id uuid.UUID) (Employee, error) {
	row := q.db.QueryRow(ctx, getEmployee, id)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.DepartmentID,
		&i.FullName,
		&i.Email,
		&i.Phone,
		&i.Position,
		&i.HireDate,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getEmployeeByEmail = `-- name: GetEmployeeByEmail :one
SELECT id, branch_id, department_id, full_name, email, phone, position, hire_date, status, created_at FROM employees
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetEmployeeByEmail(ctx context.Context, email string) (Employee, error) {
	row := q.db.QueryRow(ctx, getEmployeeByEmail, email)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.DepartmentID,
		&i.FullName,
		&i.Email,
		&i.Phone,
		&i.Position,
		&i.HireDate,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listEmployeesByBranch = `-- name: ListEmployeesByBranch :many
SELECT id, branch_id, department_id, full_name, email, phone, position, hire_date, status, created_at FROM employees
WHERE branch_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListEmployeesByBranchParams struct {
	BranchID uuid.UUID `json:"branch_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListEmployeesByBranch(ctx context.Context, arg ListEmployeesByBranchParams) ([]Employee, error) {
	rows, err := q.db.Query(ctx, listEmployeesByBranch, arg.BranchID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Employee{}
	for rows.Next() {
		var i Employee
		if err := rows.Scan(
			&i.ID,
			&i.BranchID,
			&i.DepartmentID,
			&i.FullName,
			&i.Email,
			&i.Phone,
			&i.Position,
			&i.HireDate,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEmployee = `-- name: UpdateEmployee :one
UPDATE employees
SET
    branch_id = COALESCE($2, branch_id),
    department_id = COALESCE($3, department_id),
    full_name = COALESCE($4, full_name),
    phone = COALESCE($5, phone),
    position = COALESCE($6, position),
    status = COALESCE($7, status)
WHERE id = $1
RETURNING id, branch_id, department_id, full_name, email, phone, position, hire_date, status, created_at
`

type UpdateEmployeeParams struct {
	ID           uuid.UUID   `json:"id"`
	BranchID     uuid.UUID   `json:"branch_id"`
	DepartmentID uuid.UUID   `json:"department_id"`
	FullName     string      `json:"full_name"`
	Phone        pgtype.Text `json:"phone"`
	Position     pgtype.Text `json:"position"`
	Status       pgtype.Text `json:"status"`
}

func (q *Queries) UpdateEmployee(ctx context.Context, arg UpdateEmployeeParams) (Employee, error) {
	row := q.db.QueryRow(ctx, updateEmployee,
		arg.ID,
		arg.BranchID,
		arg.DepartmentID,
		arg.FullName,
		arg.Phone,
		arg.Position,
		arg.Status,
	)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.DepartmentID,
		&i.FullName,
		&i.Email,
		&i.Phone,
		&i.Position,
		&i.HireDate,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
