// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invoices.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createInvoice = `-- name: CreateInvoice :one
INSERT INTO invoices (
    branch_id,
    order_id,
    repair_order_id,
    invoice_number,
    amount,
    due_date,
    status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, branch_id, order_id, repair_order_id, invoice_number, amount, due_date, status, issued_date
`

type CreateInvoiceParams struct {
	BranchID      uuid.UUID      `json:"branch_id"`
	OrderID       pgtype.UUID    `json:"order_id"`
	RepairOrderID pgtype.UUID    `json:"repair_order_id"`
	InvoiceNumber string         `json:"invoice_number"`
	Amount        pgtype.Numeric `json:"amount"`
	DueDate       pgtype.Date    `json:"due_date"`
	Status        pgtype.Text    `json:"status"`
}

func (q *Queries) CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, createInvoice,
		arg.BranchID,
		arg.OrderID,
		arg.RepairOrderID,
		arg.InvoiceNumber,
		arg.Amount,
		arg.DueDate,
		arg.Status,
	)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.OrderID,
		&i.RepairOrderID,
		&i.InvoiceNumber,
		&i.Amount,
		&i.DueDate,
		&i.Status,
		&i.IssuedDate,
	)
	return i, err
}

const getInvoice = `-- name: GetInvoice :one
SELECT id, branch_id, order_id, repair_order_id, invoice_number, amount, due_date, status, issued_date FROM invoices
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetInvoice(ctx context.Context, id uuid.UUID) (Invoice, error) {
	row := q.db.QueryRow(ctx, getInvoice, id)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.OrderID,
		&i.RepairOrderID,
		&i.InvoiceNumber,
		&i.Amount,
		&i.DueDate,
		&i.Status,
		&i.IssuedDate,
	)
	return i, err
}

const getInvoiceForUpdate = `-- name: GetInvoiceForUpdate :one
SELECT id, branch_id, order_id, repair_order_id, invoice_number, amount, due_date, status, issued_date FROM invoices
WHERE id = $1 LIMIT 1
FOR UPDATE
`

func (q *Queries) GetInvoiceForUpdate(ctx context.Context, id uuid.UUID) (Invoice, error) {
	row := q.db.QueryRow(ctx, getInvoiceForUpdate, id)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.OrderID,
		&i.RepairOrderID,
		&i.InvoiceNumber,
		&i.Amount,
		&i.DueDate,
		&i.Status,
		&i.IssuedDate,
	)
	return i, err
}

const getTotalPaidForInvoice = `-- name: GetTotalPaidForInvoice :one
SELECT COALESCE(SUM(amount), 0)::NUMERIC(15,2) AS total_paid
FROM transactions
WHERE invoice_id = $1
  AND branch_id = $2
  AND status = 'COMPLETED'
`

type GetTotalPaidForInvoiceParams struct {
	InvoiceID uuid.UUID `json:"invoice_id"`
	BranchID  uuid.UUID `json:"branch_id"`
}

func (q *Queries) GetTotalPaidForInvoice(ctx context.Context, arg GetTotalPaidForInvoiceParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getTotalPaidForInvoice, arg.InvoiceID, arg.BranchID)
	var total_paid pgtype.Numeric
	err := row.Scan(&total_paid)
	return total_paid, err
}

const listInvoices = `-- name: ListInvoices :many
SELECT id, branch_id, order_id, repair_order_id, invoice_number, amount, due_date, status, issued_date FROM invoices
ORDER BY issued_date DESC
LIMIT $1 OFFSET $2
`

type ListInvoicesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListInvoices(ctx context.Context, arg ListInvoicesParams) ([]Invoice, error) {
	rows, err := q.db.Query(ctx, listInvoices, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invoice{}
	for rows.Next() {
		var i Invoice
		if err := rows.Scan(
			&i.ID,
			&i.BranchID,
			&i.OrderID,
			&i.RepairOrderID,
			&i.InvoiceNumber,
			&i.Amount,
			&i.DueDate,
			&i.Status,
			&i.IssuedDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoicesByOrder = `-- name: ListInvoicesByOrder :many
SELECT id, branch_id, order_id, repair_order_id, invoice_number, amount, due_date, status, issued_date FROM invoices
WHERE order_id = $1
ORDER BY issued_date ASC
`

func (q *Queries) ListInvoicesByOrder(ctx context.Context, orderID pgtype.UUID) ([]Invoice, error) {
	rows, err := q.db.Query(ctx, listInvoicesByOrder, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invoice{}
	for rows.Next() {
		var i Invoice
		if err := rows.Scan(
			&i.ID,
			&i.BranchID,
			&i.OrderID,
			&i.RepairOrderID,
			&i.InvoiceNumber,
			&i.Amount,
			&i.DueDate,
			&i.Status,
			&i.IssuedDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoicesByStatus = `-- name: ListInvoicesByStatus :many
SELECT id, branch_id, order_id, repair_order_id, invoice_number, amount, due_date, status, issued_date FROM invoices
WHERE status = $1
ORDER BY issued_date DESC
LIMIT $2 OFFSET $3
`

type ListInvoicesByStatusParams struct {
	Status pgtype.Text `json:"status"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListInvoicesByStatus(ctx context.Context, arg ListInvoicesByStatusParams) ([]Invoice, error) {
	rows, err := q.db.Query(ctx, listInvoicesByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invoice{}
	for rows.Next() {
		var i Invoice
		if err := rows.Scan(
			&i.ID,
			&i.BranchID,
			&i.OrderID,
			&i.RepairOrderID,
			&i.InvoiceNumber,
			&i.Amount,
			&i.DueDate,
			&i.Status,
			&i.IssuedDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInvoiceStatus = `-- name: UpdateInvoiceStatus :one
UPDATE invoices
SET status = $2
WHERE id = $1
RETURNING id, branch_id, order_id, repair_order_id, invoice_number, amount, due_date, status, issued_date
`

type UpdateInvoiceStatusParams struct {
	ID     uuid.UUID   `json:"id"`
	Status pgtype.Text `json:"status"`
}

func (q *Queries) UpdateInvoiceStatus(ctx context.Context, arg UpdateInvoiceStatusParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, updateInvoiceStatus, arg.ID, arg.Status)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.OrderID,
		&i.RepairOrderID,
		&i.InvoiceNumber,
		&i.Amount,
		&i.DueDate,
		&i.Status,
		&i.IssuedDate,
	)
	return i, err
}
