// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: leads.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const assignLead = `-- name: AssignLead :one
UPDATE leads
SET
    assigned_to = $2
WHERE id = $1
RETURNING id, branch_id, customer_id, campaign_id, assigned_to, interested_model_id, status, notes, created_at
`

type AssignLeadParams struct {
	ID         uuid.UUID   `json:"id"`
	AssignedTo pgtype.UUID `json:"assigned_to"`
}

func (q *Queries) AssignLead(ctx context.Context, arg AssignLeadParams) (Lead, error) {
	row := q.db.QueryRow(ctx, assignLead, arg.ID, arg.AssignedTo)
	var i Lead
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.CustomerID,
		&i.CampaignID,
		&i.AssignedTo,
		&i.InterestedModelID,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const createLead = `-- name: CreateLead :one
INSERT INTO leads (
    branch_id,
    customer_id,
    campaign_id,
    assigned_to,
    interested_model_id,
    status,
    notes
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, branch_id, customer_id, campaign_id, assigned_to, interested_model_id, status, notes, created_at
`

type CreateLeadParams struct {
	BranchID          uuid.UUID   `json:"branch_id"`
	CustomerID        uuid.UUID   `json:"customer_id"`
	CampaignID        pgtype.UUID `json:"campaign_id"`
	AssignedTo        pgtype.UUID `json:"assigned_to"`
	InterestedModelID pgtype.UUID `json:"interested_model_id"`
	Status            string      `json:"status"`
	Notes             pgtype.Text `json:"notes"`
}

func (q *Queries) CreateLead(ctx context.Context, arg CreateLeadParams) (Lead, error) {
	row := q.db.QueryRow(ctx, createLead,
		arg.BranchID,
		arg.CustomerID,
		arg.CampaignID,
		arg.AssignedTo,
		arg.InterestedModelID,
		arg.Status,
		arg.Notes,
	)
	var i Lead
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.CustomerID,
		&i.CampaignID,
		&i.AssignedTo,
		&i.InterestedModelID,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const getLead = `-- name: GetLead :one
SELECT id, branch_id, customer_id, campaign_id, assigned_to, interested_model_id, status, notes, created_at FROM leads
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetLead(ctx context.Context, id uuid.UUID) (Lead, error) {
	row := q.db.QueryRow(ctx, getLead, id)
	var i Lead
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.CustomerID,
		&i.CampaignID,
		&i.AssignedTo,
		&i.InterestedModelID,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const listLeads = `-- name: ListLeads :many
SELECT id, branch_id, customer_id, campaign_id, assigned_to, interested_model_id, status, notes, created_at FROM leads
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListLeadsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListLeads(ctx context.Context, arg ListLeadsParams) ([]Lead, error) {
	rows, err := q.db.Query(ctx, listLeads, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Lead{}
	for rows.Next() {
		var i Lead
		if err := rows.Scan(
			&i.ID,
			&i.BranchID,
			&i.CustomerID,
			&i.CampaignID,
			&i.AssignedTo,
			&i.InterestedModelID,
			&i.Status,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLeadsByCustomer = `-- name: ListLeadsByCustomer :many
SELECT id, branch_id, customer_id, campaign_id, assigned_to, interested_model_id, status, notes, created_at FROM leads
WHERE customer_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListLeadsByCustomer(ctx context.Context, customerID uuid.UUID) ([]Lead, error) {
	rows, err := q.db.Query(ctx, listLeadsByCustomer, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Lead{}
	for rows.Next() {
		var i Lead
		if err := rows.Scan(
			&i.ID,
			&i.BranchID,
			&i.CustomerID,
			&i.CampaignID,
			&i.AssignedTo,
			&i.InterestedModelID,
			&i.Status,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLeadsByEmployee = `-- name: ListLeadsByEmployee :many
SELECT id, branch_id, customer_id, campaign_id, assigned_to, interested_model_id, status, notes, created_at FROM leads
WHERE assigned_to = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListLeadsByEmployeeParams struct {
	AssignedTo pgtype.UUID `json:"assigned_to"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
}

func (q *Queries) ListLeadsByEmployee(ctx context.Context, arg ListLeadsByEmployeeParams) ([]Lead, error) {
	rows, err := q.db.Query(ctx, listLeadsByEmployee, arg.AssignedTo, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Lead{}
	for rows.Next() {
		var i Lead
		if err := rows.Scan(
			&i.ID,
			&i.BranchID,
			&i.CustomerID,
			&i.CampaignID,
			&i.AssignedTo,
			&i.InterestedModelID,
			&i.Status,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLeadsByStatus = `-- name: ListLeadsByStatus :many
SELECT id, branch_id, customer_id, campaign_id, assigned_to, interested_model_id, status, notes, created_at FROM leads
WHERE status = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListLeadsByStatusParams struct {
	Status string `json:"status"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListLeadsByStatus(ctx context.Context, arg ListLeadsByStatusParams) ([]Lead, error) {
	rows, err := q.db.Query(ctx, listLeadsByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Lead{}
	for rows.Next() {
		var i Lead
		if err := rows.Scan(
			&i.ID,
			&i.BranchID,
			&i.CustomerID,
			&i.CampaignID,
			&i.AssignedTo,
			&i.InterestedModelID,
			&i.Status,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLeadStatus = `-- name: UpdateLeadStatus :one
UPDATE leads
SET
    status = $2,
    notes = COALESCE($3, notes)
WHERE id = $1
RETURNING id, branch_id, customer_id, campaign_id, assigned_to, interested_model_id, status, notes, created_at
`

type UpdateLeadStatusParams struct {
	ID     uuid.UUID   `json:"id"`
	Status string      `json:"status"`
	Notes  pgtype.Text `json:"notes"`
}

func (q *Queries) UpdateLeadStatus(ctx context.Context, arg UpdateLeadStatusParams) (Lead, error) {
	row := q.db.QueryRow(ctx, updateLeadStatus, arg.ID, arg.Status, arg.Notes)
	var i Lead
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.CustomerID,
		&i.CampaignID,
		&i.AssignedTo,
		&i.InterestedModelID,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}
