// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Branch struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Code      string             `json:"code"`
	Address   pgtype.Text        `json:"address"`
	TaxCode   pgtype.Text        `json:"tax_code"`
	Phone     pgtype.Text        `json:"phone"`
	Status    pgtype.Text        `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Campaign struct {
	ID        uuid.UUID      `json:"id"`
	Name      string         `json:"name"`
	Budget    pgtype.Numeric `json:"budget"`
	StartDate pgtype.Date    `json:"start_date"`
	EndDate   pgtype.Date    `json:"end_date"`
	Platform  pgtype.Text    `json:"platform"`
	Status    pgtype.Text    `json:"status"`
}

type Contract struct {
	ID             uuid.UUID          `json:"id"`
	OrderID        uuid.UUID          `json:"order_id"`
	ContractNumber string             `json:"contract_number"`
	SignedDate     pgtype.Date        `json:"signed_date"`
	FileUrl        pgtype.Text        `json:"file_url"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Customer struct {
	ID           uuid.UUID          `json:"id"`
	Type         pgtype.Text        `json:"type"`
	Name         string             `json:"name"`
	Phone        string             `json:"phone"`
	Email        pgtype.Text        `json:"email"`
	IDCardNumber pgtype.Text        `json:"id_card_number"`
	Address      pgtype.Text        `json:"address"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Department struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

type Employee struct {
	ID           uuid.UUID          `json:"id"`
	BranchID     uuid.UUID          `json:"branch_id"`
	DepartmentID uuid.UUID          `json:"department_id"`
	FullName     string             `json:"full_name"`
	Email        string             `json:"email"`
	Phone        pgtype.Text        `json:"phone"`
	Position     pgtype.Text        `json:"position"`
	HireDate     pgtype.Date        `json:"hire_date"`
	Status       pgtype.Text        `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Invoice struct {
	ID            uuid.UUID          `json:"id"`
	BranchID      uuid.UUID          `json:"branch_id"`
	OrderID       pgtype.UUID        `json:"order_id"`
	RepairOrderID pgtype.UUID        `json:"repair_order_id"`
	InvoiceNumber string             `json:"invoice_number"`
	Amount        pgtype.Numeric     `json:"amount"`
	DueDate       pgtype.Date        `json:"due_date"`
	Status        pgtype.Text        `json:"status"`
	IssuedDate    pgtype.Timestamptz `json:"issued_date"`
}

type Lead struct {
	ID                uuid.UUID          `json:"id"`
	BranchID          uuid.UUID          `json:"branch_id"`
	CustomerID        uuid.UUID          `json:"customer_id"`
	CampaignID        pgtype.UUID        `json:"campaign_id"`
	AssignedTo        pgtype.UUID        `json:"assigned_to"`
	InterestedModelID pgtype.UUID        `json:"interested_model_id"`
	Status            string             `json:"status"`
	Notes             pgtype.Text        `json:"notes"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type RepairOrder struct {
	ID                     uuid.UUID          `json:"id"`
	BranchID               uuid.UUID          `json:"branch_id"`
	CustomerID             uuid.UUID          `json:"customer_id"`
	VehicleID              uuid.UUID          `json:"vehicle_id"`
	ServiceAdvisorID       uuid.UUID          `json:"service_advisor_id"`
	MechanicID             pgtype.UUID        `json:"mechanic_id"`
	Odometer               int32              `json:"odometer"`
	Symptoms               pgtype.Text        `json:"symptoms"`
	Diagnosis              pgtype.Text        `json:"diagnosis"`
	TotalCost              pgtype.Numeric     `json:"total_cost"`
	Status                 string             `json:"status"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	OdometerOverrideReason pgtype.Text        `json:"odometer_override_reason"`
}

type RepairOrderItem struct {
	ID            uuid.UUID      `json:"id"`
	RepairOrderID uuid.UUID      `json:"repair_order_id"`
	ItemType      string         `json:"item_type"`
	ItemName      string         `json:"item_name"`
	Quantity      int32          `json:"quantity"`
	UnitPrice     pgtype.Numeric `json:"unit_price"`
	Subtotal      pgtype.Numeric `json:"subtotal"`
	PartID        pgtype.UUID    `json:"part_id"`
}

type SalesOrder struct {
	ID                uuid.UUID          `json:"id"`
	BranchID          uuid.UUID          `json:"branch_id"`
	CustomerID        uuid.UUID          `json:"customer_id"`
	SalespersonID     uuid.UUID          `json:"salesperson_id"`
	VehicleID         uuid.UUID          `json:"vehicle_id"`
	TotalAmount       pgtype.Numeric     `json:"total_amount"`
	DiscountAmount    pgtype.Numeric     `json:"discount_amount"`
	DepositAmount     pgtype.Numeric     `json:"deposit_amount"`
	Status            string             `json:"status"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	CancelReason      pgtype.Text        `json:"cancel_reason"`
	DepositResolution pgtype.Text        `json:"deposit_resolution"`
	CancelledBy       pgtype.UUID        `json:"cancelled_by"`
	CancelledAt       pgtype.Timestamptz `json:"cancelled_at"`
}

type Session struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	RefreshToken string             `json:"refresh_token"`
	UserAgent    pgtype.Text        `json:"user_agent"`
	ClientIp     pgtype.Text        `json:"client_ip"`
	IsBlocked    pgtype.Bool        `json:"is_blocked"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Transaction struct {
	ID              uuid.UUID          `json:"id"`
	BranchID        uuid.UUID          `json:"branch_id"`
	InvoiceID       uuid.UUID          `json:"invoice_id"`
	PaymentMethod   string             `json:"payment_method"`
	Amount          pgtype.Numeric     `json:"amount"`
	TransactionDate pgtype.Timestamptz `json:"transaction_date"`
	Status          pgtype.Text        `json:"status"`
	Note            pgtype.Text        `json:"note"`
	ReferenceCode   pgtype.Text        `json:"reference_code"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	EmployeeID   uuid.UUID          `json:"employee_id"`
	Username     string             `json:"username"`
	PasswordHash string             `json:"password_hash"`
	Role         string             `json:"role"`
	IsActive     pgtype.Bool        `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Vehicle struct {
	ID            uuid.UUID          `json:"id"`
	BranchID      uuid.UUID          `json:"branch_id"`
	ModelID       uuid.UUID          `json:"model_id"`
	Vin           string             `json:"vin"`
	EngineNumber  pgtype.Text        `json:"engine_number"`
	ColorExterior pgtype.Text        `json:"color_exterior"`
	ColorInterior pgtype.Text        `json:"color_interior"`
	Status        string             `json:"status"`
	PurchasePrice pgtype.Numeric     `json:"purchase_price"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type VehicleModel struct {
	ID             uuid.UUID          `json:"id"`
	Make           string             `json:"make"`
	Model          string             `json:"model"`
	Year           int32              `json:"year"`
	Trim           pgtype.Text        `json:"trim"`
	Specifications []byte             `json:"specifications"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}
