// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sales_orders.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cancelSalesOrder = `-- name: CancelSalesOrder :one
UPDATE sales_orders
SET
    status = 'CANCELLED',
    cancel_reason = $2,
    deposit_resolution = $3,
    cancelled_by = $4,
    cancelled_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, branch_id, customer_id, salesperson_id, vehicle_id, total_amount, discount_amount, deposit_amount, status, created_at, updated_at, cancel_reason, deposit_resolution, cancelled_by, cancelled_at
`

type CancelSalesOrderParams struct {
	ID                uuid.UUID   `json:"id"`
	CancelReason      pgtype.Text `json:"cancel_reason"`
	DepositResolution pgtype.Text `json:"deposit_resolution"`
	CancelledBy       pgtype.UUID `json:"cancelled_by"`
}

func (q *Queries) CancelSalesOrder(ctx context.Context, arg CancelSalesOrderParams) (SalesOrder, error) {
	row := q.db.QueryRow(ctx, cancelSalesOrder,
		arg.ID,
		arg.CancelReason,
		arg.DepositResolution,
		arg.CancelledBy,
	)
	var i SalesOrder
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.CustomerID,
		&i.SalespersonID,
		&i.VehicleID,
		&i.TotalAmount,
		&i.DiscountAmount,
		&i.DepositAmount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CancelReason,
		&i.DepositResolution,
		&i.CancelledBy,
		&i.CancelledAt,
	)
	return i, err
}

const createSalesOrder = `-- name: CreateSalesOrder :one
INSERT INTO sales_orders (
    branch_id,
    customer_id,
    salesperson_id,
    vehicle_id,
    total_amount,
    discount_amount,
    deposit_amount,
    status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, branch_id, customer_id, salesperson_id, vehicle_id, total_amount, discount_amount, deposit_amount, status, created_at, updated_at, cancel_reason, deposit_resolution, cancelled_by, cancelled_at
`

type CreateSalesOrderParams struct {
	BranchID       uuid.UUID      `json:"branch_id"`
	CustomerID     uuid.UUID      `json:"customer_id"`
	SalespersonID  uuid.UUID      `json:"salesperson_id"`
	VehicleID      uuid.UUID      `json:"vehicle_id"`
	TotalAmount    pgtype.Numeric `json:"total_amount"`
	DiscountAmount pgtype.Numeric `json:"discount_amount"`
	DepositAmount  pgtype.Numeric `json:"deposit_amount"`
	Status         string         `json:"status"`
}

func (q *Queries) CreateSalesOrder(ctx context.Context, arg CreateSalesOrderParams) (SalesOrder, error) {
	row := q.db.QueryRow(ctx, createSalesOrder,
		arg.BranchID,
		arg.CustomerID,
		arg.SalespersonID,
		arg.VehicleID,
		arg.TotalAmount,
		arg.DiscountAmount,
		arg.DepositAmount,
		arg.Status,
	)
	var i SalesOrder
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.CustomerID,
		&i.SalespersonID,
		&i.VehicleID,
		&i.TotalAmount,
		&i.DiscountAmount,
		&i.DepositAmount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CancelReason,
		&i.DepositResolution,
		&i.CancelledBy,
		&i.CancelledAt,
	)
	return i, err
}

const getSalesOrder = `-- name: GetSalesOrder :one
SELECT id, branch_id, customer_id, salesperson_id, vehicle_id, total_amount, discount_amount, deposit_amount, status, created_at, updated_at, cancel_reason, deposit_resolution, cancelled_by, cancelled_at FROM sales_orders
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetSalesOrder(ctx context.Context, id uuid.UUID) (SalesOrder, error) {
	row := q.db.QueryRow(ctx, getSalesOrder, id)
	var i SalesOrder
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.CustomerID,
		&i.SalespersonID,
		&i.VehicleID,
		&i.TotalAmount,
		&i.DiscountAmount,
		&i.DepositAmount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CancelReason,
		&i.DepositResolution,
		&i.CancelledBy,
		&i.CancelledAt,
	)
	return i, err
}

const getSalesOrderByVehicleID = `-- name: GetSalesOrderByVehicleID :one
SELECT id, branch_id, customer_id, salesperson_id, vehicle_id, total_amount, discount_amount, deposit_amount, status, created_at, updated_at, cancel_reason, deposit_resolution, cancelled_by, cancelled_at FROM sales_orders
WHERE vehicle_id = $1 LIMIT 1
`

func (q *Queries) GetSalesOrderByVehicleID(ctx context.Context, vehicleID uuid.UUID) (SalesOrder, error) {
	row := q.db.QueryRow(ctx, getSalesOrderByVehicleID, vehicleID)
	var i SalesOrder
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.CustomerID,
		&i.SalespersonID,
		&i.VehicleID,
		&i.TotalAmount,
		&i.DiscountAmount,
		&i.DepositAmount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CancelReason,
		&i.DepositResolution,
		&i.CancelledBy,
		&i.CancelledAt,
	)
	return i, err
}

const getSalesOrderForUpdate = `-- name: GetSalesOrderForUpdate :one
SELECT id, branch_id, customer_id, salesperson_id, vehicle_id, total_amount, discount_amount, deposit_amount, status, created_at, updated_at, cancel_reason, deposit_resolution, cancelled_by, cancelled_at FROM sales_orders
WHERE id = $1 LIMIT 1
FOR UPDATE
`

func (q *Queries) GetSalesOrderForUpdate(ctx context.Context, id uuid.UUID) (SalesOrder, error) {
	row := q.db.QueryRow(ctx, getSalesOrderForUpdate, id)
	var i SalesOrder
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.CustomerID,
		&i.SalespersonID,
		&i.VehicleID,
		&i.TotalAmount,
		&i.DiscountAmount,
		&i.DepositAmount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CancelReason,
		&i.DepositResolution,
		&i.CancelledBy,
		&i.CancelledAt,
	)
	return i, err
}

const listSalesOrders = `-- name: ListSalesOrders :many
SELECT id, branch_id, customer_id, salesperson_id, vehicle_id, total_amount, discount_amount, deposit_amount, status, created_at, updated_at, cancel_reason, deposit_resolution, cancelled_by, cancelled_at FROM sales_orders
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListSalesOrdersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListSalesOrders(ctx context.Context, arg ListSalesOrdersParams) ([]SalesOrder, error) {
	rows, err := q.db.Query(ctx, listSalesOrders, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SalesOrder{}
	for rows.Next() {
		var i SalesOrder
		if err := rows.Scan(
			&i.ID,
			&i.BranchID,
			&i.CustomerID,
			&i.SalespersonID,
			&i.VehicleID,
			&i.TotalAmount,
			&i.DiscountAmount,
			&i.DepositAmount,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CancelReason,
			&i.DepositResolution,
			&i.CancelledBy,
			&i.CancelledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSalesOrdersByCustomer = `-- name: ListSalesOrdersByCustomer :many
SELECT id, branch_id, customer_id, salesperson_id, vehicle_id, total_amount, discount_amount, deposit_amount, status, created_at, updated_at, cancel_reason, deposit_resolution, cancelled_by, cancelled_at FROM sales_orders
WHERE customer_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListSalesOrdersByCustomer(ctx context.Context, customerID uuid.UUID) ([]SalesOrder, error) {
	rows, err := q.db.Query(ctx, listSalesOrdersByCustomer, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SalesOrder{}
	for rows.Next() {
		var i SalesOrder
		if err := rows.Scan(
			&i.ID,
			&i.BranchID,
			&i.CustomerID,
			&i.SalespersonID,
			&i.VehicleID,
			&i.TotalAmount,
			&i.DiscountAmount,
			&i.DepositAmount,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CancelReason,
			&i.DepositResolution,
			&i.CancelledBy,
			&i.CancelledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSalesOrdersBySalesperson = `-- name: ListSalesOrdersBySalesperson :many
SELECT id, branch_id, customer_id, salesperson_id, vehicle_id, total_amount, discount_amount, deposit_amount, status, created_at, updated_at, cancel_reason, deposit_resolution, cancelled_by, cancelled_at FROM sales_orders
WHERE salesperson_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListSalesOrdersBySalespersonParams struct {
	SalespersonID uuid.UUID `json:"salesperson_id"`
	Limit         int32     `json:"limit"`
	Offset        int32     `json:"offset"`
}

func (q *Queries) ListSalesOrdersBySalesperson(ctx context.Context, arg ListSalesOrdersBySalespersonParams) ([]SalesOrder, error) {
	rows, err := q.db.Query(ctx, listSalesOrdersBySalesperson, arg.SalespersonID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SalesOrder{}
	for rows.Next() {
		var i SalesOrder
		if err := rows.Scan(
			&i.ID,
			&i.BranchID,
			&i.CustomerID,
			&i.SalespersonID,
			&i.VehicleID,
			&i.TotalAmount,
			&i.DiscountAmount,
			&i.DepositAmount,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CancelReason,
			&i.DepositResolution,
			&i.CancelledBy,
			&i.CancelledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSalesOrdersByStatus = `-- name: ListSalesOrdersByStatus :many
SELECT id, branch_id, customer_id, salesperson_id, vehicle_id, total_amount, discount_amount, deposit_amount, status, created_at, updated_at, cancel_reason, deposit_resolution, cancelled_by, cancelled_at FROM sales_orders
WHERE status = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListSalesOrdersByStatusParams struct {
	Status string `json:"status"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListSalesOrdersByStatus(ctx context.Context, arg ListSalesOrdersByStatusParams) ([]SalesOrder, error) {
	rows, err := q.db.Query(ctx, listSalesOrdersByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SalesOrder{}
	for rows.Next() {
		var i SalesOrder
		if err := rows.Scan(
			&i.ID,
			&i.BranchID,
			&i.CustomerID,
			&i.SalespersonID,
			&i.VehicleID,
			&i.TotalAmount,
			&i.DiscountAmount,
			&i.DepositAmount,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CancelReason,
			&i.DepositResolution,
			&i.CancelledBy,
			&i.CancelledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSalesOrderDeposit = `-- name: UpdateSalesOrderDeposit :one
UPDATE sales_orders
SET
    deposit_amount = $2,
    status = $3,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, branch_id, customer_id, salesperson_id, vehicle_id, total_amount, discount_amount, deposit_amount, status, created_at, updated_at, cancel_reason, deposit_resolution, cancelled_by, cancelled_at
`

type UpdateSalesOrderDepositParams struct {
	ID            uuid.UUID      `json:"id"`
	DepositAmount pgtype.Numeric `json:"deposit_amount"`
	Status        string         `json:"status"`
}

func (q *Queries) UpdateSalesOrderDeposit(ctx context.Context, arg UpdateSalesOrderDepositParams) (SalesOrder, error) {
	row := q.db.QueryRow(ctx, updateSalesOrderDeposit, arg.ID, arg.DepositAmount, arg.Status)
	var i SalesOrder
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.CustomerID,
		&i.SalespersonID,
		&i.VehicleID,
		&i.TotalAmount,
		&i.DiscountAmount,
		&i.DepositAmount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CancelReason,
		&i.DepositResolution,
		&i.CancelledBy,
		&i.CancelledAt,
	)
	return i, err
}

const updateSalesOrderStatus = `-- name: UpdateSalesOrderStatus :one
UPDATE sales_orders
SET
    status = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, branch_id, customer_id, salesperson_id, vehicle_id, total_amount, discount_amount, deposit_amount, status, created_at, updated_at, cancel_reason, deposit_resolution, cancelled_by, cancelled_at
`

type UpdateSalesOrderStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateSalesOrderStatus(ctx context.Context, arg UpdateSalesOrderStatusParams) (SalesOrder, error) {
	row := q.db.QueryRow(ctx, updateSalesOrderStatus, arg.ID, arg.Status)
	var i SalesOrder
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.CustomerID,
		&i.SalespersonID,
		&i.VehicleID,
		&i.TotalAmount,
		&i.DiscountAmount,
		&i.DepositAmount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CancelReason,
		&i.DepositResolution,
		&i.CancelledBy,
		&i.CancelledAt,
	)
	return i, err
}
