// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
    branch_id,
    invoice_id,
    payment_method,
    amount,
    status,
    note,
    reference_code
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, branch_id, invoice_id, payment_method, amount, transaction_date, status, note, reference_code
`

type CreateTransactionParams struct {
	BranchID      uuid.UUID      `json:"branch_id"`
	InvoiceID     uuid.UUID      `json:"invoice_id"`
	PaymentMethod string         `json:"payment_method"`
	Amount        pgtype.Numeric `json:"amount"`
	Status        pgtype.Text    `json:"status"`
	Note          pgtype.Text    `json:"note"`
	ReferenceCode pgtype.Text    `json:"reference_code"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.BranchID,
		arg.InvoiceID,
		arg.PaymentMethod,
		arg.Amount,
		arg.Status,
		arg.Note,
		arg.ReferenceCode,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.InvoiceID,
		&i.PaymentMethod,
		&i.Amount,
		&i.TransactionDate,
		&i.Status,
		&i.Note,
		&i.ReferenceCode,
	)
	return i, err
}

const getTotalPaidForOrder = `-- name: GetTotalPaidForOrder :one
SELECT COALESCE(SUM(t.amount), 0)::NUMERIC(15,2) AS total_paid
FROM transactions t
JOIN invoices i ON t.invoice_id = i.id
WHERE i.order_id = $1
  AND i.branch_id = $2
  AND t.branch_id = $2
  AND t.status = 'COMPLETED'
`

type GetTotalPaidForOrderParams struct {
	OrderID  pgtype.UUID `json:"order_id"`
	BranchID uuid.UUID   `json:"branch_id"`
}

func (q *Queries) GetTotalPaidForOrder(ctx context.Context, arg GetTotalPaidForOrderParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getTotalPaidForOrder, arg.OrderID, arg.BranchID)
	var total_paid pgtype.Numeric
	err := row.Scan(&total_paid)
	return total_paid, err
}

const getTransaction = `-- name: GetTransaction :one
SELECT id, branch_id, invoice_id, payment_method, amount, transaction_date, status, note, reference_code FROM transactions
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTransaction(ctx context.Context, id uuid.UUID) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransaction, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.InvoiceID,
		&i.PaymentMethod,
		&i.Amount,
		&i.TransactionDate,
		&i.Status,
		&i.Note,
		&i.ReferenceCode,
	)
	return i, err
}

const getTransactionByReferenceCode = `-- name: GetTransactionByReferenceCode :one
SELECT id, branch_id, invoice_id, payment_method, amount, transaction_date, status, note, reference_code FROM transactions
WHERE reference_code = $1 LIMIT 1
`

func (q *Queries) GetTransactionByReferenceCode(ctx context.Context, referenceCode pgtype.Text) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByReferenceCode, referenceCode)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.InvoiceID,
		&i.PaymentMethod,
		&i.Amount,
		&i.TransactionDate,
		&i.Status,
		&i.Note,
		&i.ReferenceCode,
	)
	return i, err
}

const listTransactions = `-- name: ListTransactions :many
SELECT id, branch_id, invoice_id, payment_method, amount, transaction_date, status, note, reference_code FROM transactions
ORDER BY transaction_date DESC
LIMIT $1 OFFSET $2
`

type ListTransactionsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.BranchID,
			&i.InvoiceID,
			&i.PaymentMethod,
			&i.Amount,
			&i.TransactionDate,
			&i.Status,
			&i.Note,
			&i.ReferenceCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByInvoice = `-- name: ListTransactionsByInvoice :many
SELECT id, branch_id, invoice_id, payment_method, amount, transaction_date, status, note, reference_code FROM transactions
WHERE invoice_id = $1
ORDER BY transaction_date DESC
`

func (q *Queries) ListTransactionsByInvoice(ctx context.Context, invoiceID uuid.UUID) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsByInvoice, invoiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.BranchID,
			&i.InvoiceID,
			&i.PaymentMethod,
			&i.Amount,
			&i.TransactionDate,
			&i.Status,
			&i.Note,
			&i.ReferenceCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
