// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    employee_id,
    username,
    password_hash,
    role,
    is_active
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, employee_id, username, password_hash, role, is_active, created_at
`

type CreateUserParams struct {
	EmployeeID   uuid.UUID   `json:"employee_id"`
	Username     string      `json:"username"`
	PasswordHash string      `json:"password_hash"`
	Role         string      `json:"role"`
	IsActive     pgtype.Bool `json:"is_active"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.EmployeeID,
		arg.Username,
		arg.PasswordHash,
		arg.Role,
		arg.IsActive,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmployeeID = `-- name: GetUserByEmployeeID :one
SELECT id, employee_id, username, password_hash, role, is_active, created_at FROM users
WHERE employee_id = $1 LIMIT 1
`

func (q *Queries) GetUserByEmployeeID(ctx context.Context, employeeID uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmployeeID, employeeID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, employee_id, username, password_hash, role, is_active, created_at FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, employee_id, username, password_hash, role, is_active, created_at FROM users
WHERE username = $1 LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :one
UPDATE users
SET password_hash = $2
WHERE id = $1
RETURNING id, employee_id, username, password_hash, role, is_active, created_at
`

type UpdateUserPasswordParams struct {
	ID           uuid.UUID `json:"id"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserStatus = `-- name: UpdateUserStatus :one
UPDATE users
SET is_active = $2
WHERE id = $1
RETURNING id, employee_id, username, password_hash, role, is_active, created_at
`

type UpdateUserStatusParams struct {
	ID       uuid.UUID   `json:"id"`
	IsActive pgtype.Bool `json:"is_active"`
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserStatus, arg.ID, arg.IsActive)
	var i User
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}
