// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vehicle_models.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createVehicleModel = `-- name: CreateVehicleModel :one
INSERT INTO vehicle_models (
    make,
    model,
    year,
    trim,
    specifications
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, make, model, year, trim, specifications, created_at
`

type CreateVehicleModelParams struct {
	Make           string      `json:"make"`
	Model          string      `json:"model"`
	Year           int32       `json:"year"`
	Trim           pgtype.Text `json:"trim"`
	Specifications []byte      `json:"specifications"`
}

func (q *Queries) CreateVehicleModel(ctx context.Context, arg CreateVehicleModelParams) (VehicleModel, error) {
	row := q.db.QueryRow(ctx, createVehicleModel,
		arg.Make,
		arg.Model,
		arg.Year,
		arg.Trim,
		arg.Specifications,
	)
	var i VehicleModel
	err := row.Scan(
		&i.ID,
		&i.Make,
		&i.Model,
		&i.Year,
		&i.Trim,
		&i.Specifications,
		&i.CreatedAt,
	)
	return i, err
}

const deleteVehicleModel = `-- name: DeleteVehicleModel :exec
DELETE FROM vehicle_models
WHERE id = $1
`

func (q *Queries) DeleteVehicleModel(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteVehicleModel, id)
	return err
}

const getVehicleModel = `-- name: GetVehicleModel :one
SELECT id, make, model, year, trim, specifications, created_at FROM vehicle_models
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetVehicleModel(ctx context.Context, id uuid.UUID) (VehicleModel, error) {
	row := q.db.QueryRow(ctx, getVehicleModel, id)
	var i VehicleModel
	err := row.Scan(
		&i.ID,
		&i.Make,
		&i.Model,
		&i.Year,
		&i.Trim,
		&i.Specifications,
		&i.CreatedAt,
	)
	return i, err
}

const listVehicleModels = `-- name: ListVehicleModels :many
SELECT id, make, model, year, trim, specifications, created_at FROM vehicle_models
ORDER BY make ASC, model ASC, year DESC
LIMIT $1 OFFSET $2
`

type ListVehicleModelsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListVehicleModels(ctx context.Context, arg ListVehicleModelsParams) ([]VehicleModel, error) {
	rows, err := q.db.Query(ctx, listVehicleModels, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VehicleModel{}
	for rows.Next() {
		var i VehicleModel
		if err := rows.Scan(
			&i.ID,
			&i.Make,
			&i.Model,
			&i.Year,
			&i.Trim,
			&i.Specifications,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVehicleModelsByMake = `-- name: ListVehicleModelsByMake :many
SELECT id, make, model, year, trim, specifications, created_at FROM vehicle_models
WHERE make ILIKE $1
ORDER BY model ASC, year DESC
LIMIT $2 OFFSET $3
`

type ListVehicleModelsByMakeParams struct {
	Make   string `json:"make"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListVehicleModelsByMake(ctx context.Context, arg ListVehicleModelsByMakeParams) ([]VehicleModel, error) {
	rows, err := q.db.Query(ctx, listVehicleModelsByMake, arg.Make, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VehicleModel{}
	for rows.Next() {
		var i VehicleModel
		if err := rows.Scan(
			&i.ID,
			&i.Make,
			&i.Model,
			&i.Year,
			&i.Trim,
			&i.Specifications,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVehicleModel = `-- name: UpdateVehicleModel :one
UPDATE vehicle_models
SET
    make = COALESCE($2, make),
    model = COALESCE($3, model),
    year = COALESCE($4, year),
    trim = COALESCE($5, trim),
    specifications = COALESCE($6, specifications)
WHERE id = $1
RETURNING id, make, model, year, trim, specifications, created_at
`

type UpdateVehicleModelParams struct {
	ID             uuid.UUID   `json:"id"`
	Make           string      `json:"make"`
	Model          string      `json:"model"`
	Year           int32       `json:"year"`
	Trim           pgtype.Text `json:"trim"`
	Specifications []byte      `json:"specifications"`
}

func (q *Queries) UpdateVehicleModel(ctx context.Context, arg UpdateVehicleModelParams) (VehicleModel, error) {
	row := q.db.QueryRow(ctx, updateVehicleModel,
		arg.ID,
		arg.Make,
		arg.Model,
		arg.Year,
		arg.Trim,
		arg.Specifications,
	)
	var i VehicleModel
	err := row.Scan(
		&i.ID,
		&i.Make,
		&i.Model,
		&i.Year,
		&i.Trim,
		&i.Specifications,
		&i.CreatedAt,
	)
	return i, err
}
