// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vehicles.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createVehicle = `-- name: CreateVehicle :one
INSERT INTO vehicles (
    branch_id,
    model_id,
    vin,
    engine_number,
    color_exterior,
    color_interior,
    status,
    purchase_price
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, branch_id, model_id, vin, engine_number, color_exterior, color_interior, status, purchase_price, created_at
`

type CreateVehicleParams struct {
	BranchID      uuid.UUID      `json:"branch_id"`
	ModelID       uuid.UUID      `json:"model_id"`
	Vin           string         `json:"vin"`
	EngineNumber  pgtype.Text    `json:"engine_number"`
	ColorExterior pgtype.Text    `json:"color_exterior"`
	ColorInterior pgtype.Text    `json:"color_interior"`
	Status        string         `json:"status"`
	PurchasePrice pgtype.Numeric `json:"purchase_price"`
}

func (q *Queries) CreateVehicle(ctx context.Context, arg CreateVehicleParams) (Vehicle, error) {
	row := q.db.QueryRow(ctx, createVehicle,
		arg.BranchID,
		arg.ModelID,
		arg.Vin,
		arg.EngineNumber,
		arg.ColorExterior,
		arg.ColorInterior,
		arg.Status,
		arg.PurchasePrice,
	)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.ModelID,
		&i.Vin,
		&i.EngineNumber,
		&i.ColorExterior,
		&i.ColorInterior,
		&i.Status,
		&i.PurchasePrice,
		&i.CreatedAt,
	)
	return i, err
}

const deleteVehicle = `-- name: DeleteVehicle :exec
DELETE FROM vehicles
WHERE id = $1
`

func (q *Queries) DeleteVehicle(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteVehicle, id)
	return err
}

const getVehicle = `-- name: GetVehicle :one
SELECT id, branch_id, model_id, vin, engine_number, color_exterior, color_interior, status, purchase_price, created_at FROM vehicles
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetVehicle(ctx context.Context, id uuid.UUID) (Vehicle, error) {
	row := q.db.QueryRow(ctx, getVehicle, id)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.ModelID,
		&i.Vin,
		&i.EngineNumber,
		&i.ColorExterior,
		&i.ColorInterior,
		&i.Status,
		&i.PurchasePrice,
		&i.CreatedAt,
	)
	return i, err
}

const getVehicleByVIN = `-- name: GetVehicleByVIN :one
SELECT id, branch_id, model_id, vin, engine_number, color_exterior, color_interior, status, purchase_price, created_at FROM vehicles
WHERE vin = $1 LIMIT 1
`

func (q *Queries) GetVehicleByVIN(ctx context.Context, vin string) (Vehicle, error) {
	row := q.db.QueryRow(ctx, getVehicleByVIN, vin)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.ModelID,
		&i.Vin,
		&i.EngineNumber,
		&i.ColorExterior,
		&i.ColorInterior,
		&i.Status,
		&i.PurchasePrice,
		&i.CreatedAt,
	)
	return i, err
}

const getVehicleForUpdate = `-- name: GetVehicleForUpdate :one
SELECT id, branch_id, model_id, vin, engine_number, color_exterior, color_interior, status, purchase_price, created_at FROM vehicles
WHERE id = $1 LIMIT 1
FOR UPDATE
`

func (q *Queries) GetVehicleForUpdate(ctx context.Context, id uuid.UUID) (Vehicle, error) {
	row := q.db.QueryRow(ctx, getVehicleForUpdate, id)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.ModelID,
		&i.Vin,
		&i.EngineNumber,
		&i.ColorExterior,
		&i.ColorInterior,
		&i.Status,
		&i.PurchasePrice,
		&i.CreatedAt,
	)
	return i, err
}

const listVehicles = `-- name: ListVehicles :many
SELECT id, branch_id, model_id, vin, engine_number, color_exterior, color_interior, status, purchase_price, created_at FROM vehicles
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListVehiclesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListVehicles(ctx context.Context, arg ListVehiclesParams) ([]Vehicle, error) {
	rows, err := q.db.Query(ctx, listVehicles, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Vehicle{}
	for rows.Next() {
		var i Vehicle
		if err := rows.Scan(
			&i.ID,
			&i.BranchID,
			&i.ModelID,
			&i.Vin,
			&i.EngineNumber,
			&i.ColorExterior,
			&i.ColorInterior,
			&i.Status,
			&i.PurchasePrice,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVehiclesByBranch = `-- name: ListVehiclesByBranch :many
SELECT id, branch_id, model_id, vin, engine_number, color_exterior, color_interior, status, purchase_price, created_at FROM vehicles
WHERE branch_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListVehiclesByBranchParams struct {
	BranchID uuid.UUID `json:"branch_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListVehiclesByBranch(ctx context.Context, arg ListVehiclesByBranchParams) ([]Vehicle, error) {
	rows, err := q.db.Query(ctx, listVehiclesByBranch, arg.BranchID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Vehicle{}
	for rows.Next() {
		var i Vehicle
		if err := rows.Scan(
			&i.ID,
			&i.BranchID,
			&i.ModelID,
			&i.Vin,
			&i.EngineNumber,
			&i.ColorExterior,
			&i.ColorInterior,
			&i.Status,
			&i.PurchasePrice,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVehiclesByBranchAndStatus = `-- name: ListVehiclesByBranchAndStatus :many
SELECT id, branch_id, model_id, vin, engine_number, color_exterior, color_interior, status, purchase_price, created_at FROM vehicles
WHERE branch_id = $1 AND status = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListVehiclesByBranchAndStatusParams struct {
	BranchID uuid.UUID `json:"branch_id"`
	Status   string    `json:"status"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListVehiclesByBranchAndStatus(ctx context.Context, arg ListVehiclesByBranchAndStatusParams) ([]Vehicle, error) {
	rows, err := q.db.Query(ctx, listVehiclesByBranchAndStatus,
		arg.BranchID,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Vehicle{}
	for rows.Next() {
		var i Vehicle
		if err := rows.Scan(
			&i.ID,
			&i.BranchID,
			&i.ModelID,
			&i.Vin,
			&i.EngineNumber,
			&i.ColorExterior,
			&i.ColorInterior,
			&i.Status,
			&i.PurchasePrice,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVehiclesByStatus = `-- name: ListVehiclesByStatus :many
SELECT id, branch_id, model_id, vin, engine_number, color_exterior, color_interior, status, purchase_price, created_at FROM vehicles
WHERE status = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListVehiclesByStatusParams struct {
	Status string `json:"status"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListVehiclesByStatus(ctx context.Context, arg ListVehiclesByStatusParams) ([]Vehicle, error) {
	rows, err := q.db.Query(ctx, listVehiclesByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Vehicle{}
	for rows.Next() {
		var i Vehicle
		if err := rows.Scan(
			&i.ID,
			&i.BranchID,
			&i.ModelID,
			&i.Vin,
			&i.EngineNumber,
			&i.ColorExterior,
			&i.ColorInterior,
			&i.Status,
			&i.PurchasePrice,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const transferVehicleBranch = `-- name: TransferVehicleBranch :one
UPDATE vehicles
SET
    branch_id = $2,
    status = 'IN_TRANSIT'
WHERE id = $1
RETURNING id, branch_id, model_id, vin, engine_number, color_exterior, color_interior, status, purchase_price, created_at
`

type TransferVehicleBranchParams struct {
	ID       uuid.UUID `json:"id"`
	BranchID uuid.UUID `json:"branch_id"`
}

func (q *Queries) TransferVehicleBranch(ctx context.Context, arg TransferVehicleBranchParams) (Vehicle, error) {
	row := q.db.QueryRow(ctx, transferVehicleBranch, arg.ID, arg.BranchID)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.ModelID,
		&i.Vin,
		&i.EngineNumber,
		&i.ColorExterior,
		&i.ColorInterior,
		&i.Status,
		&i.PurchasePrice,
		&i.CreatedAt,
	)
	return i, err
}

const updateVehicleDetails = `-- name: UpdateVehicleDetails :one
UPDATE vehicles
SET
    engine_number = COALESCE($2, engine_number),
    color_exterior = COALESCE($3, color_exterior),
    color_interior = COALESCE($4, color_interior),
    purchase_price = COALESCE($5, purchase_price)
WHERE id = $1
RETURNING id, branch_id, model_id, vin, engine_number, color_exterior, color_interior, status, purchase_price, created_at
`

type UpdateVehicleDetailsParams struct {
	ID            uuid.UUID      `json:"id"`
	EngineNumber  pgtype.Text    `json:"engine_number"`
	ColorExterior pgtype.Text    `json:"color_exterior"`
	ColorInterior pgtype.Text    `json:"color_interior"`
	PurchasePrice pgtype.Numeric `json:"purchase_price"`
}

func (q *Queries) UpdateVehicleDetails(ctx context.Context, arg UpdateVehicleDetailsParams) (Vehicle, error) {
	row := q.db.QueryRow(ctx, updateVehicleDetails,
		arg.ID,
		arg.EngineNumber,
		arg.ColorExterior,
		arg.ColorInterior,
		arg.PurchasePrice,
	)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.ModelID,
		&i.Vin,
		&i.EngineNumber,
		&i.ColorExterior,
		&i.ColorInterior,
		&i.Status,
		&i.PurchasePrice,
		&i.CreatedAt,
	)
	return i, err
}

const updateVehicleStatus = `-- name: UpdateVehicleStatus :one
UPDATE vehicles
SET status = $2
WHERE id = $1
RETURNING id, branch_id, model_id, vin, engine_number, color_exterior, color_interior, status, purchase_price, created_at
`

type UpdateVehicleStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateVehicleStatus(ctx context.Context, arg UpdateVehicleStatusParams) (Vehicle, error) {
	row := q.db.QueryRow(ctx, updateVehicleStatus, arg.ID, arg.Status)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.ModelID,
		&i.Vin,
		&i.EngineNumber,
		&i.ColorExterior,
		&i.ColorInterior,
		&i.Status,
		&i.PurchasePrice,
		&i.CreatedAt,
	)
	return i, err
}
